### ISSUE TITLE
can't build with yarn 2

### ISSUE THREAD

**Issue by bbigras** [mui-org/material-ui-pickers#1717]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/xTiTncVep2khPGhK1i/giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.10       |
| material-ui          |     4.9.12    |
| TypeScript           |  3.7.2       |
| React                |   16.13.1      |
| Browser              |         |
| Peer library         |  date-fns  2.12.0    |  |

## Steps to reproduce

1. mkdir test
2. cd test
3. yarn set version berry
4. yarn dlx create-react-app my-app --template typescript
5. cd my-app
6. yarn add @material-ui/core
7. yarn add @material-ui/pickers @date-io/date-fns@1.x date-fns
7. add a date picker or something to App.tsx
8. yarn start

I tried to set the following in .yarnrc but with no success:
```yaml
packageExtensions:
  "@material-ui/pickers@*":
    peerDependencies:
      "prop-types": "*"
```

## Actual behavior

```
Failed to compile.

./.yarn/$$virtual/@material-ui-pickers-virtual-3136547978/0/cache/@material-ui-pickers-npm-3.2.10-2d3cf5f048-2.zip/node_modules/@material-ui/pickers/esm/Calendar-11ae61f6.js
Module not found: @material-ui/pickers tried to access prop-types (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```

**Comment by oliviertassinari** [comment]
@bbigras We have moved our effort to the `next` branch (v4.0.0-alpha.5 as we are speaking), can you reproduce with the next version?

**Comment by bbigras** [comment]
Yes I still have this with 4.0.0-alpha.5:
```
./.yarn/cache/jss-plugin-rule-value-function-npm-10.1.1-f63c97f8af-2.zip/node_modules/jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.esm.js
Module not found: jss-plugin-rule-value-function tried to access tiny-warning, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

Thanks a lot for pointing me in the right direction, and you time. Merci.

**Comment by oliviertassinari** [comment]
@bbigras Which duplicate with https://github.com/mui-org/material-ui/issues/20797 and https://github.com/cssinjs/jss/issues/1313. Happy to hear we have no other issues with `@material-ui/pickers@v4.0.0-alpha.5` :)

**Comment by bbigras** [comment]
:+1: 

and if someone else has the same problem, this seems to work:

EDIT: I think you need to run `yarn` after the edit.

.yarnrc.yml
```yaml
yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "@material-ui/pickers@*":
    dependencies:
      "prop-types": "*"
  "jss-plugin-rule-value-function@*":
    dependencies:
      "tiny-warning": "*"
```
